
services:
  app:
    image: ghcr.io/hugocorrea01/saude-solidaria-front-spring:master
    container_name: saude-solidaria-prod
    env_file: .env.prod
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: production
      SPRING_DATA_MONGODB_URI: mongodb+srv://<user>:<pass>@<cluster>.mongodb.net/saude_solidaria
    restart: always
