
services:
  app:
    image: ghcr.io/hugocorrea01/saude-solidaria-front-spring:master
    container_name: saude-solidaria-prod
    env_file: .env.prod
    ports:
      - "8080:8080"
    restart: always
