services:
  app:
    image: ghcr.io/hugocorrea01/saude-solidaria-front-spring:Hugo
    container_name: saude-solidaria-staging
    env_file: .env.staging
    ports:
      - "80:8080"
    environment:
        SPRING_PROFILES_ACTIVE: staging
        SPRING_DATA_MONGODB_URI: mongodb+srv://<user>:<pass>@<cluster>.mongodb.net/saude_solidaria
    restart: always
